version: '3'

services:
  ubuntu-16.04:
    image: th3s/pwn-env:ubuntu-16.04
    container_name: pwn-env_ubuntu-16.04
    volumes:
      - ./challenge:/challenge
      - ./config:/root/.config
      - ./deps:/deps
      - ./ssh:/root/.ssh
    ports:
      - '22160:22'
      - '61604:8888'
    expose:
      - '22'
      - '8888'

  ubuntu-18.04:
    image: th3s/pwn-env:ubuntu-18.04
    container_name: pwn-env_ubuntu-18.04
    volumes:
      - ./challenge:/challenge
      - ./config:/root/.config
      - ./deps:/deps
      - ./ssh:/root/.ssh
    ports:
      - '22180:22'
      - '61804:8888'
    expose:
      - '22'
      - '8888'

  ubuntu-20.04:
    image: th3s/pwn-env:ubuntu-20.04
    container_name: pwn-env_ubuntu-20.04
    volumes:
      - ./challenge:/challenge
      - ./config:/root/.config
      - ./deps:/deps
      - ./ssh:/root/.ssh
    ports:
      - '22200:22'
      - '62004:8888'
    expose:
      - '22'
      - '8888'

  ubuntu-22.04:
    image: th3s/pwn-env:ubuntu-22.04
    container_name: pwn-env_ubuntu-22.04
    volumes:
      - ./challenge:/challenge
      - ./config:/root/.config
      - ./deps:/deps
      - ./ssh:/root/.ssh
    ports:
      - '22220:22'
      - '62204:8888'
    expose:
      - '22'
      - '8888'
