name: Build Docker Images (Ubuntu Archive)

on:
  workflow_dispatch:

jobs:
  init-build-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get All Changed Files
        id: step2
        run: |
          git fetch --depth=2
          git diff --name-only "HEAD^" > /tmp/changed_files.txt
          echo "changed_files=$(paste -sd "," /tmp/changed_files.txt)" >> "$GITHUB_OUTPUT"
          cat /tmp/changed_files.txt

      - name: Install Dependencies
        run: bash ./setup.sh

      - name: Compress Folder
        run: zip -r /tmp/artifact.zip . -x ".git/*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-artifact
          path: /tmp/artifact.zip

    outputs:
      changed-files: ${{ steps.step2.outputs.changed_files }}

  build-ubuntu1704:
    runs-on: ubuntu-latest
    needs: [init-build-env]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: env-artifact
          path: .

      - name: Decompress Artifact
        run: unzip artifact.zip -d .

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./build/ubuntu/non-lts/17.04/Dockerfile
          push: true
          tags: th3s/pwn-env:ubuntu-17.04

  build-ubuntu1710:
    runs-on: ubuntu-latest
    needs: [init-build-env]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: env-artifact
          path: .

      - name: Decompress Artifact
        run: unzip artifact.zip -d .

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./build/ubuntu/non-lts/17.10/Dockerfile
          push: true
          tags: th3s/pwn-env:ubuntu-17.10

  build-ubuntu1810:
    runs-on: ubuntu-latest
    needs: [init-build-env]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: env-artifact
          path: .

      - name: Decompress Artifact
        run: unzip artifact.zip -d .

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./build/ubuntu/non-lts/18.10/Dockerfile
          push: true
          tags: th3s/pwn-env:ubuntu-18.10
